// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Infrastructure.DataAccess;

#nullable disable

namespace Trading.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Trading.Infrastructure.DataAccess.Entities.MarketPriceStateEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentAskPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBidPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentSpread")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentSpreadPercent")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousAskPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousBidPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousMarketPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousSpread")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousSpreadPercent")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreviousTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.ToTable("MarketPriceStates", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Orders_OrderId");

                    b.HasIndex("Symbol", "Timestamp")
                        .HasDatabaseName("IX_Orders_Symbol_Timestamp");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.DataAccess.Entities.OrderRejectionReasonEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntityId")
                        .HasDatabaseName("IX_OrderRejectionReasons_OrderEntityId");

                    b.ToTable("OrderRejectionReasons", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.DataAccess.Entities.TradingRulesEntity", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DuplicateIdPreventionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxNotional")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxQuantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceDeviationPercent")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SymbolWhitelistEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolWhitelistJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Version");

                    b.ToTable("TradingRules", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.DataAccess.Entities.OrderRejectionReasonEntity", b =>
                {
                    b.HasOne("Trading.Infrastructure.DataAccess.Entities.OrderEntity", null)
                        .WithMany("RejectionReasons")
                        .HasForeignKey("OrderEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Infrastructure.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Navigation("RejectionReasons");
                });
#pragma warning restore 612, 618
        }
    }
}
